# Generated by Django 5.1.5 on 2025-02-03 21:43

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_site_remove_userlink_site_userlink_custom_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlink',
            name='sites',
        ),
        migrations.AddField(
            model_name='userlink',
            name='site',
            field=models.ForeignKey(default=website.models.get_default_site, on_delete=django.db.models.deletion.CASCADE, to='website.site'),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='custom_text',
            field=models.CharField(blank=True, help_text='Extra text for the link', max_length=50),
        ),
    ]
