# Generated by Django 5.1.5 on 2025-02-05 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_userlink_sites_userlink_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.userlink')),
            ],
        ),
    ]
