# Generated by Django 5.1.5 on 2025-02-05 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_linkclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.userlink')),
            ],
        ),
    ]
